genetic_algorithm:
  population_size: 1000
  mutation_rate: 0.2
  crossover_rate: 0.8
  elite_size: 25
  generations: 50
  simulation_runs: 10

loot_table:
  nb_tiers: 4
  price_range_min: 3
  price_range_max: 50
  max_prob: 0.65
  min_prob: 0.04
  target_expected_value: 8.5
